repos:
- repo: https://github.com/python/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.5.0
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
  - id: flake8